### ISSUE TITLE
Incorrect reporting of junior racers

### ISSUE THREAD

**Issue by snakr1** [OnTheDay-net/bug-reports#6]
Hello,
My name is Lloyd Davies and I am the new Treasurer of the Northern California/Nevada Cycling Association.  I have been trying to understand the sources of our revenue which has lead me to look closely at the end of day reports for a number of races during 2023.  I noticed that in a number (perhaps all) of races they number of juniors in the race is misreported which has lead to promotors paying less to the NCNCA for races than they should have.  I have three examples which are detailed below.  Perhaps you could look into this and confirm my findings. 

As a separate matter, in 2024 the NCNCA will be charging promoters the same rate for junior racers as they do for adult racers so there is no need to show a deduction for junior racers on your end of day report as you do currently.  Somewhat related to this Chief Referees have been incorrectly reporting to USAC the number of unique racers to USA Cycling and have been excluding junior racers from the number of unique racers.  The happens in some but not all cases and seems to vary by race and Chief Referee.  I will be working with the head of the Chief Referees in our region to correct this situation but eliminating the deduction for juniors on your End of Day Report will go a long way to fixing this problem as well.

Please reach out to me to discuss if you have any questions.  

Regards,  Lloyd Davies
Treasurer, NCNCA

----------------
Spreadsheet with results of all 4 races below attached.
[Copper Valley CR EOD Rpt.pdf](https://github.com/OnTheDay-net/bug-reports/files/14143366/Copper.Valley.CR.EOD.Rpt.pdf)
[Pine Flat RR EOD Rpt.pdf](https://github.com/OnTheDay-net/bug-reports/files/14143368/Pine.Flat.RR.EOD.Rpt.pdf)
[Livermore Crit EOD Rpt.pdf](https://github.com/OnTheDay-net/bug-reports/files/14143369/Livermore.Crit.EOD.Rpt.pdf)
[Winchester Circuit Race EOD Rpt.pdf](https://github.com/OnTheDay-net/bug-reports/files/14143370/Winchester.Circuit.Race.EOD.Rpt.pdf)
[To OnTheDay.net.xlsx](https://github.com/OnTheDay-net/bug-reports/files/14143373/To.OnTheDay.net.xlsx)

1)  Pine Flat Road Race, Permit 6823, 2/19/2023
- Total racers 115 on the results sheet at USAC and Road-results.com versus 114 per OTD End of Day Report
- No juniors raced in this race but End of Date Report says there were 2 juniors
https://www.road-results.com/race/15227
End of Date Report attached to this email

2) Winchester Circuit Race, Permit 7310 , 5/13/2023
End of day report says there were 3 juniors but there was only 1 by the name of Ryan Lerner.
EOD rpt attached.
PDF file of results as reported to USA Cycling and road-results.com also attached.

3) Copper Valley Circuit Race, permit 7069, 3/5/2023
EOD rpt says there were 4 juniors but there were only 2 by the names of Grant Edmister and Marco Infosino.
EOD rpt attached
PDF file of results as reported to USA Cycling and road-results.com also attached.

4) Livermore Crit, Permit 4893, 2/12/2023
Total racers on EOD rpt is 1 more than reported to USAC as results and duplicates were 64 in results versus 63 in EOD report.  Net number is the same in EOD rpt and in reported results.
Number of juniors is incorrect 22 in the EOD rpt vs 16 in reality and in results as reported.

**Comment by richardbrockie** [comment]
We've connected directly via email so I will close this ticket.
